# Generated by Django 3.0.5 on 2020-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
    ]
