# Generated by Django 3.0.5 on 2020-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completes_on',
            field=models.DateTimeField(null=True),
        ),
    ]
