# Generated by Django 3.0.5 on 2020-06-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_completes_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='action',
        ),
    ]
