# Generated by Django 3.0.5 on 2020-06-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200613_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completes_on',
            new_name='completed_on',
        ),
    ]
